### ISSUE TITLE
PHP 8.2 Fatal related to Symfony

### ISSUE THREAD

**Issue by weitzman** [code-lts/doctum#57]
I'm using PHP 8.2 and the latest Doctum Phar and am seeing the following error in my [Github Actions build](https://github.com/drush-ops/drush/actions/runs/4265142262/jobs/7424125494).

```
> php $HOME/bin/doctum.phar --ansi --ignore-parse-errors update doctum-config.php '--only-version=12.x'
PHP Fatal error:  Uncaught ErrorException: Deprecated: Using ${var} in strings is deprecated, use {$var} instead in phar:///home/runner/bin/doctum.phar/vendor/symfony/console/Command/DumpCompletionCommand.php line 48 in phar:///home/runner/bin/doctum.phar/src/ErrorHandler.php:53
Stack trace:
#0 phar:///home/runner/bin/doctum.phar/vendor/composer/ClassLoader.php(571): Doctum\ErrorHandler->handle()
#1 phar:///home/runner/bin/doctum.phar/vendor/composer/ClassLoader.php(571): include()
#2 phar:///home/runner/bin/doctum.phar/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 phar:///home/runner/bin/doctum.phar/vendor/symfony/console/Application.php(1092): Composer\Autoload\ClassLoader->loadClass()
#4 phar:///home/runner/bin/doctum.phar/vendor/symfony/console/Application.php(1272): Symfony\Component\Console\Application->getDefaultCommands()
#5 phar:///home/runner/bin/doctum.phar/vendor/symfony/console/Application.php(514): Symfony\Component\Console\Application->init()
#6 phar:///home/runner/bin/doctum.phar/src/Console/Application.php(34): Symfony\Component\Console\Application->add()
#7 phar:///home/runner/bin/doctum.phar/bin/doctum-binary.php(25): Doctum\Console\Application->__construct()
#8 /home/runner/bin/doctum.phar(16): include('...')
#9 {main}
  thrown in phar:///home/runner/bin/doctum.phar/src/ErrorHandler.php on line 53
Script php $HOME/bin/doctum.phar --ansi --ignore-parse-errors update doctum-config.php handling the api event returned with error code 255
Error: Process completed with exit code 255.
```

**Comment by williamdes** [comment]
I think I will re-trigger a re-build to have 8.2 compat on the phar.
Thank you for reporting this !

Is there anything else you would like on Doctum ?

Except #56 that has #51 open

**Comment by williamdes** [comment]
This will be released today 🎉

**Comment by williamdes** [comment]
Done, let me know if it works with 5.5.2 ?
